### PR TITLE
make valet support fedora

### PR DESCRIPTION
**Pull request by sunznx**
I use fedora, and this change seem ok for me with the remi-php repo enabled.

### CODE REVIEW

**Comment by jmarcher** [comment]
Is there any previous configuration needed for Fedora? As you said remi-php and something else?

Do you think your Fedora code could work for other distributions that use RPM or is your implementation Fedora dependent?

**Comment by sunznx** [comment]
http://rpms.famillecollet.com/  

remi repo contains php56 php70 php71..

other distributions that use RPM like redhat should use yum, rather than dnf. I only run on my laptop (fedora 24)

**Comment by jmarcher** [comment]
Why did you closed this PR? does it have problems?

**Comment by jmarcher** [comment]
ping @sunznx I would love to have support for Fedora :+1: confirm if working please and thanks for your work

**Pull request merged**
